### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Saklad5** [q231950/rorschach#7]
Is this project open-source? If so, which license does it use? Apache is common for Swift, if I may make a suggestion.

**Comment by q231950** [comment]
Hi @Saklad5 thanks for the reminder! It's open source, let me think about the license for a moment - I'll consider Apache, thanks. Feel free to fork/include into your project. Since I'm on vacation I might take a bit to make the changes.

**Comment by q231950** [comment]
Just merged #8  thanks again @Saklad5!
